### PR TITLE
[v0.13.2] [proguard] fixed issues with dropped themis symbols ==> master

### PR DESCRIPTION
**Pull request by dodikk**
Basically solved by adding `proguard.cfg` with the following test. 

```
-keep class com.cossacklabs.themis.**
-keep class com.cossacklabs.themis.** {*;}
```

Discussions in `cossacklabs/themis` repositoruy issue
https://github.com/cossacklabs/themis/issues/716

### CODE REVIEW

**Comment by dodikk** [comment]
Not merging yet to `master` until properly tested.

**Comment by vixentael** [comment]
thank you @dodikk!

**Comment by dodikk** [comment]
No issues with these fixes after a period of testing.
Merging to `master`.

**Comment by vixentael** [comment]
💃💃💃

**Pull request merged**
